services:
  go:
    container_name: ${GO_CONTAINER_HOST}
    hostname: ${GO_HOST}
    env_file: .env
    tty: true
    build:
      context: .
      dockerfile: ./docker/go/Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ./src:/python/src/app